name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  http: ^1.5.0
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  path: ^1.9.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  workmanager:
   git:
     url: https://github.com/fluttercommunity/flutter_workmanager.git
     path: workmanager
     ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
